#!/bin/bash

#------------------------------------------------------------
#  alias
#------------------------------------------------------------
alias ls="gls --color=auto"
alias find=gfind
alias xargs=gxargs

# GNUコマンドのエイリアスを設定
# setup aliases for GNU coreutils/findutils
if [ "$PS1" ] && [ -f '/usr/local/Cellar/coreutils/8.10/aliases' ]; then
  source /usr/local/Cellar/coreutils/8.10/aliases
fi

#------------------------------------------------------------
#  bash completion
#------------------------------------------------------------
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

#------------------------------------------------------------
#  SSH鍵管理をOSXのキーチェーンにさせない
#------------------------------------------------------------

#if [ ! -f $HOME/.keychain/$HOSTNAME-sh ] ; then
#  unset SSH_AUTH_SOCK
#fi
#eval `keychain --eval --agents ssh id_rsa`

